
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: documentmanager
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  migrate:
    build: .
    depends_on:
      - db
    env_file:
      - .env
    command: sh -c "npx prisma migrate dev --name init --skip-seed --preview-feature"
    volumes:
      - .:/usr/src/app

  app:
    build: .
    depends_on:
      - db
      - migrate
    ports:
      - '3000:3000'
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    command: npm start

  test:
    build: .
    depends_on:
      - db
      - migrate
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    command: npm test --verbose

volumes:
  db_data:
